version: '3.2'
services:
  java-dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    # ports:
    #   - 8888:8888
    volumes:
      - ..:/home/developer/workspace
    deploy:
      resources:
        # reservations:
        #   devices:
        #     - capabilities: [gpu]
        limits:
          # limit cpu usage to prevent system hangs
          cpus: '0.70'